version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: metazone-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=redis://redis:6379
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      - redis

  frontend:
    build:
      context: ./client
    container_name: metazone-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: shopforge-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
