apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://your-user:your-password@cluster.mongodb.net/shopforge?retryWrites=true&w=majority"
